name: kafka-cmars
version: '2.1.0'
summary: Apache Kafka is a distributed streaming platform
description: |
    Kafka is generally used for two broad classes of applications:
    - Building real-time streaming data pipelines that reliably get data between systems or applications
    - Building real-time streaming applications that transform or react to the streams of data 

grade: stable
confinement: strict

apps:
  kafka:
    command: start-kafka-wrapper.bash
    daemon: simple
    plugs: [network, network-bind]
  zookeeper:
    command: start-zookeeper-wrapper.bash
    daemon: simple
    plugs: [network, network-bind]

parts:
  deps:
    stage-packages:
    - default-jre-headless
    build-packages:
    - default-jdk-headless
    plugin: nil
  kafka:
    plugin: gradle
    source: .
    override-build: |-
      cp ../../../snap/local/*.bash $SNAPCRAFT_PART_INSTALL
      ./gradlew releaseTarGz
      tarball=$(pwd)/core/build/distributions/kafka_2.11-2.1.0.tgz
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/kafka
      (cd $SNAPCRAFT_PART_INSTALL/opt/kafka; tar --strip-components=1 -xzvf $tarball)
    stage:
    - opt
    - start-kafka-wrapper.bash
    - start-zookeeper-wrapper.bash
    prime:
    - opt
    - start-kafka-wrapper.bash
    - start-zookeeper-wrapper.bash
